version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower

  nodejs-app:
    image: vkantanen/nodejs-app
    ports:
      - 8080:8080
    container_name: nodejs-app
