version: '3.8'

services:
  backend:
    build: ./example-backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - REQUEST_ORIGIN=http://frontend:5000

  frontend:
    build: ./example-frontend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080

  redis:
    image: redis:7-alpine

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/var/lib/postgresql/data

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
